mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.message.model

server:
  port: 6666

logging:
  level:
    org.wlxy.example.dao : debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  application:
    name: message-server
  cloud:
    inetutils:
      default-ip-address: 60.205.212.112
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    timeout: 5000
  datasource:
    url: jdbc:mysql://39.108.127.117:3306/Architecture_design?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,wall,slf4j,config
      max-active: 100
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 50
      max-pool-prepared-statement-per-connection-size: 20

app:
  imgPath: /root/JavaPro/img/
  info: 在线文档
  author: BitC
  email: 276819708@qq.com
  swaggerTitle: swagger测试文档
  swaggerContactName: 钟贤伟
  swaggerContactWebUrl: https://www.bitcoc.top
  swaggerContactEmail: 276819708@qq.com
  swaggerVersion: v1.0
  swaggerDescription: shop 在线接口文档
  swaggerTermsOfServiceUrl: https://www.bitcoc.top


eureka:
  client:
    service-url:
      defaultZone: http://39.108.127.117:10000/eureka/,http://60.205.212.112:10000/eureka/
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    ip-address: 60.205.212.112
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}